version: '3.7'

name: 'container-beconect'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=projects

